AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    hbr-cognito-test

    SAM Template for creating some tests and showcases when connecting lambda and cognito.
    
Globals:
    Function:
        Timeout: 3
        Runtime: nodejs8.10

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: hello-world/
            Handler: app.lambdaHandler
            Events:
                HelloWorld:
                    Type: Api 
                    Properties:
                        Path: /test
                        Method: get
    
    CreateUserFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: create-user/
            Handler: app.lambdaHandler
            Environment:
                Variables:
                    USERPOOLID: !Ref CognitoUserPool
            Policies:
                -
                    Version: '2012-10-17' # Policy Document
                    Statement:
                        -
                            Effect: Allow
                            Action: 
                                - cognito-identity:*
                                - cognito-idp:*
                                - cognito-sync:*
                            Resource: !GetAtt CognitoUserPool.Arn
            Events:
                CreateUser:
                    Type: Api 
                    Properties:
                        Path: /create-user
                        Method: post
    ListUsersFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: list-users/
            Handler: app.lambdaHandler
            Environment:
                Variables:
                    USERPOOLID: !Ref CognitoUserPool
            Policies:
                -
                    Version: '2012-10-17' # Policy Document
                    Statement:
                        -
                            Effect: Allow
                            Action: 
                                - cognito-identity:*
                                - cognito-idp:*
                                - cognito-sync:*
                            Resource: !GetAtt CognitoUserPool.Arn
            Events:
                ListUser:
                    Type: Api 
                    Properties:
                        Path: /list-users
                        Method: get
    
    CognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: hbr-test1-user-pool
            UsernameAttributes:
                - email
            AutoVerifiedAttributes:
                - email
Outputs:
    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn

    CreateUserFunctionIamRole:
      Description: "Implicit IAM Role created for Create User function"
      Value: !GetAtt CreateUserFunctionRole.Arn

    ListUsersFunctionIamRole:
      Description: "Implicit IAM Role created for List Users function"
      Value: !GetAtt ListUsersFunctionRole.Arn

    UserPoolId:
        Value: !Ref CognitoUserPool

